name: Health check
on:
  push:
    branches: [main]

jobs:
  health_check_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://full-stack-open-pokedex-542l.onrender.com/health
          max-attempts: 3
          retry-delay: 3s
